### ISSUE TITLE
Future compatibility with React 19

### ISSUE THREAD

**Issue by gregmsanderson** [zaichaopan/react-aria-components-tailwind-starter#15]
With React 19 now stable, I see they have removed JSX from the global namespace. As a result you get a `Cannot find namespace JSX` error wherever using it.

For example on this line:

https://github.com/zaichaopan/react-aria-components-tailwind-starter/blob/master/src/notification-badge.tsx#L14

The simplest solution appears to be to prefix `JSX` with `React`. This solves the error. For example:

`JSX.IntrinsicElements["div"]`

... should be ...

`React.JSX.IntrinsicElements["div"]`

**Comment by zaichaopan** [comment]
Thanks @gregmsanderson. JSX is replaced with React.JSX
